name: List changed pages

on:
  pull_request:
  push:
  
jobs:
  debug:
    name: URLs
    runs-on: ubuntu-latest
 
    steps:
    - id: files
      uses: jitterbit/get-changed-files@v1
    - run: |
        for changed_file in ${{ steps.files.outputs.all }}; do
          echo "Do something with this ${changed_file}."
        done
